services:
  lottery:
    image: ghcr.io/numvers/lottery:${TAG:-main}
    ports:
      - 8080:8080
    labels:
      com.centurylinklabs.watchtower.enable: true

  watchtower:
    image: containrrr/watchtower
    depends_on:
      - lottery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Seoul
    command: --interval 60 --label-enable --debug
